---
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Be careful - this will delete all of your endpoints!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# - name: Delete ALL Endpoints
#   hosts: ise_deployment
#   vars_files:
#     - credentials.yaml
#   # vars_prompt:
#   #   - name: delete_confirmation
#   #     prompt: 🛑 You want to DELETE ALL Endpoints [yes/no]?
#   #     private: no
#   #     # confirm: yes
#   gather_facts: no
#   tasks:


  - name: Get all Endpoints
    cisco.ise.endpoint_info:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
    register: result


  - name: List Endpoints by Name (YAML)
    when: result and result != []
    delegate_to: localhost
    changed_when: false
    vars:
      query: "[*].name"
    ansible.builtin.shell: 'echo "{{ result.ise_response
    | community.general.json_query(query) 
    | to_nice_yaml(indent=2) }}" > /dev/tty'


  - name: Delete all Endpoints
    when: result and result != []
    # when: delete_confirmation.lower() in ['confirm','si','t','true','y','yes']
    loop: "{{ result.ise_response }}"
    cisco.ise.endpoint:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: absent
      id: "{{ item.id }}"


...