---
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Be careful - this will delete all of your network devices!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# - name: Delete ALL Network Devices
#   hosts: ise_deployment
#   vars_files:
#     - credentials.yaml
#   # vars_prompt:
#   #   - name: delete_confirmation
#   #     prompt: 🛑 You want to DELETE ALL Network Devices [yes/no]?
#   #     private: no
#   #     # confirm: yes
#   gather_facts: no
#   tasks:


  - name: Get all NetworkDevices
    cisco.ise.network_device_info:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
    register: result

  # - name: result
  #   ansible.builtin.debug: var=result


  - name: List Network Devices by Name (YAML)
    when: result and result != []
    delegate_to: localhost
    ansible.builtin.shell: 'echo "{{ result.ise_response
    | community.general.json_query(query) 
    | to_nice_yaml(indent=2) }}" > /dev/tty'
    changed_when: false
    vars:
      query: "[*].name"


  - name: Delete all NetworkDevices by id
    when: result and result != []
    # when: delete_confirmation.lower() in ['confirm','si','t','true','y','yes']
    cisco.ise.network_device:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: absent
      id: "{{ item.id }}"
    loop: "{{ result.ise_response }}"


...