---
#
# List all Network Device Group names and configurations in YAML lists.
#
- name: List All Network Device Groups by Name (YAML)
  hosts: ise_deployment
  vars_files:
    - credentials.yaml
  gather_facts: no
  tasks:


  - name: Get All Network Device Groups (id/name/description)
    cisco.ise.network_device_group_info:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
    register: result


  - name: Result
    ansible.builtin.debug: var=result


  - name: Remove link attribute
    when: result and result != []
    loop: "{{ result.ise_response }}"
    delegate_to: localhost
    vars: 
      resources: []
    ansible.builtin.set_fact:
      resources: '{{ resources + [ item | dict2items | rejectattr("key", "equalto", "link") | list | items2dict ] }}'


  # - name: List Network Device Groups by Name (YAML)
  #   when: result and result != []
  #   loop: "{{ result.ise_response }}"
  #   delegate_to: localhost
  #   changed_when: false
  #   ansible.builtin.set_fact:
  #     resources: '{{ resources + [ item.id , item.name ] }}'

  - ansible.builtin.shell: 'echo "{{ resources | to_nice_yaml(indent=2) }}" > /dev/tty'
    delegate_to: localhost

  # - name: List Network Device Groups by Name (YAML)
  #   when: result and result != []
  #   delegate_to: localhost
  #   changed_when: false
  #   vars:
  #     query: "[*].name"
  #   ansible.builtin.shell: 'echo "{{ result.ise_response
  #   | community.general.json_query(query) 
  #   | to_nice_yaml(indent=2) }}" > /dev/tty'

...