---
# - name: Show Repository Play
#   hosts: ise_deployment
#   # vars:
#   vars_files:
#     - credentials.yaml
#   gather_facts: no
#   tasks:


  - name: Get all Repository
    cisco.ise.repository_info:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
    register: result

  - name: Result
    ansible.builtin.debug: var=result


  - name: Get Repository by Name
    when: result and result != []
    loop: "{{ result.ise_response }}"
    cisco.ise.repository_info:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      name: "{{ item.name }}"
    register: result

  - name: Result
    ansible.builtin.debug: var=result


  - name: Remove link attribute from all resources
    when: result and result != []
    loop: "{{ result.results }}"
    vars: 
      resources: []
    ansible.builtin.set_fact:
      resources: '{{ resources + [ item.ise_response | dict2items | rejectattr("key", "equalto", "link") | list | items2dict ] }}'


  - name: Dump Internal Users (YAML)
    when: resources and resources != []
    delegate_to: localhost
    changed_when: false
    ansible.builtin.shell: "echo '{{ resources | to_nice_yaml(indent=2) }}' > /dev/tty"


  - name: Summary of Internal Users by Name (YAML)
    when: resources and resources != []
    delegate_to: localhost
    changed_when: false
    vars:
      query: "[*].name"
    ansible.builtin.shell: "echo '{{ resources
    | community.general.json_query(query) 
    | to_nice_yaml(indent=2) }}' > /dev/tty"


