---
#
# ISE Endpoint Groups
#
# - name: Show Endpoint Groups Play
#   hosts: ise_deployment
#   vars_files:
#     - credentials.yaml
#   gather_facts: no
#   tasks:

  - name: Get All Endpoint Groups
    cisco.ise.endpoint_group_info:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
    register: result


  # - name: Result
  #   ansible.builtin.debug: var=result


  - name: Get Endpoints by ID
    loop: "{{ result.ise_response }}"
    cisco.ise.endpoint_group_info:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      id: "{{ item.id }}"
    register: details


  # - name: Debug details
  #   ansible.builtin.debug: var=details


  - name: Remove link attribute from all resources in loop
    ansible.builtin.set_fact:
      resources: '{{ resources + [ item.ise_response | dict2items | rejectattr("key", "equalto", "link") | list | items2dict ] }}'
    loop: "{{ details.results }}"
    vars: 
      resources: []


  # - name: Debug resources
  #   ansible.builtin.debug: var=resources


  - name: Dump Endpoint Groups (YAML)
    when: resources != []
    delegate_to: localhost
    changed_when: false
    ansible.builtin.shell: "echo '{{ resources
    | to_nice_yaml(indent=2) }}' > /dev/tty"


  - name: Concatenate ID + Name into a string
    when: resources != []
    loop: "{{ result.ise_response }}"
    vars: 
      id_names: []
    ansible.builtin.set_fact:
      id_names: "{{ id_names + [ item.id + ' ' + item.name  ] }}"


  - name: Summary of Endpoint Groups by ID/Name (YAML)
    when: id_names != []
    delegate_to: localhost
    changed_when: false
    ansible.builtin.shell: "echo '{{ id_names
    | to_nice_yaml(indent=2) }}' > /dev/tty"


...