---
#
# - Dump the ISE Active Directory configurations as YAML
# #
# - name: Dump All Active Directory Join Points (YAML)
#   hosts: ise_deployment
#   vars_files:
#     - credentials.yaml
#   gather_facts: no
#   tasks:


  - name: Get All Active Directory Join Points (id/name/description)
    cisco.ise.active_directory_info:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
    register: result


  - name: Result
    ansible.builtin.debug: var=result


  - name: Get Active Directory Details by ID
    when: result != []
    loop: "{{ result.ise_response }}"
    cisco.ise.active_directory_info:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      id: "{{ item.id }}"
    register: details


  - name: Debug details
    ansible.builtin.debug: var=details


  - name: Remove link attribute from all resources
    vars: 
      resources: []
    loop: "{{ details.results }}"
    ansible.builtin.set_fact:
      resources: "{{ resources + [ item.ise_response | dict2items | rejectattr('key', 'equalto', 'link') | list | items2dict ] }}"

  - name: Debug resources
    ansible.builtin.debug: var=resources


  - name: Dump Active Directory Configuration in ISE (YAML)
    when: resources != []
    delegate_to: localhost
    changed_when: false
    ansible.builtin.shell: "echo '{{ resources | to_nice_yaml(indent=2) }}' > /dev/tty"


  - name: YAML-ise Resource(s)
    when: resources and resources != []
    changed_when: false
    delegate_to: localhost
    ansible.builtin.copy:
      dest: "network_access_policy_set_info.yaml"
      content: |
        ---
        #
        # This configuration was auto-generated!
        #
        - name: Create Active Directory Join Points
          register: result
          cisco.ise.active_directory:
            ise_hostname: "{{{{ inventory_hostname }}}}"
            ise_username: "{{{{ ise_username }}}}"
            ise_password: "{{{{ ise_password }}}}"
            ise_verify: "{{{{ ise_verify }}}}"
            state: present
          {{ resources | to_nice_yaml(indent=2) }}
        ...



  - name: Summarize Active Directory Join Points by Name (YAML)
    when: resources != []
    delegate_to: localhost
    changed_when: false
    vars:
      query: "[*].name"
    ansible.builtin.shell: 'echo "{{ resources
    | community.general.json_query(query) 
    | to_nice_yaml(indent=2) }}" > /dev/tty'


...