---
#
# Create Endpoints
#

  #
  # Loop over multiple endpoints using vars or vars_files
  #
  - name: Printers 
    loop: "{{ macs }}"
    vars:
      endpoint_type: Printers
      description: Printers
      groupId: 22c6c780-8c00-11e6-996c-525400b48521  # Epson-Device
      macs:
        - 00-00-AA-41-8C-A8
        - 00-00-AA-C0-93-18
        - 00-00-AA-C8-66-92
    cisco.ise.endpoint:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: present
      mac: "{{ item }}"
      name: "{{ endpoint_type }}"
      description: "{{ description | default() }}"
      staticGroupAssignment: true
      groupId: "{{ groupId }}"
      # ▼▼▼ optional attributes ▼▼▼
      # staticProfileAssignment: true
      # profileId: 0a9c6890-8c00-11e6-996c-525400b48521
      # customAttributes:
      #   customAttributes:
      #     Created: "{{ created | default(now()) }}"
      #     Expired: 


...