---
#
# Create Endpoints
#

  #
  # Loop over multiple endpoints using vars or vars_files
  #
  - name: IP Phones
    loop: "{{ macs }}"
    vars:
      endpoint_type: IP Phones
      description: IP Phones
      groupId: 14f5cac0-8c00-11e6-996c-525400b48521  # Cisco-IP-Phone
      macs:
        - 00-11-BB-EF-EE-66
        - 00-11-BB-5F-C4-28
        - 00-11-BB-9E-57-BC
    cisco.ise.endpoint:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: present
      mac: "{{ item }}"
      name: "{{ endpoint_type }}"
      description: "{{ description | default() }}"
      staticGroupAssignment: true
      groupId: "{{ groupId }}"
      # ▼▼▼ optional attributes ▼▼▼
      # staticGroupAssignment: "{{ item.staticGroupAssignment | default( staticGroupAssignment_default ) }}"
      # groupId: "{{ item.groupId | default( groupId_default ) }}"
      # staticProfileAssignment: true
      # profileId: 0a9c6890-8c00-11e6-996c-525400b48521
      # customAttributes:
      #   customAttributes:
      #     Created: "{{ created | default(now()) }}"
      #     Expired: 


...